name: Build Kernel for A51 (AOSP)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y bash git make libssl-dev curl bc pkg-config m4 libtool automake autoconf python3

    - name: Download and extract WeebX Clang
      run: |
        wget "$(curl -s https://raw.githubusercontent.com/XSans0/WeebX-Clang/main/main/link.txt)" -O weebx-clang.tar.gz
        rm -rf clang && mkdir clang
        tar -xvf weebx-clang.tar.gz -C clang
        rm -f weebx-clang.tar.gz

    - name: Set up toolchain environment
      run: |
        echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH

    - name: Build the kernel
      run: |
        python3 build_kernel.py --target=a51 --allow-dirty --aosp

    - name: Upload compiled kernel
      uses: actions/upload-artifact@v3.1.3
      with:
        name: kernel-output
        path: out/arch/arm64/boot/
